### ISSUE TITLE
Fix labels on edges/links

### ISSUE THREAD

**Issue by ronhitchens** [overstory/sw-poc#10]
I managed to break this and after several hours could not get it working again.  This is probably something to do with the tick() processing not finding the text labels properly to transform them.  Or possibly they are not now being attached to the edges properly.

**Comment by smagu** [comment]
Issue was with link nesting, that was fixed with commit 1fd9aa0. Text node within SVG was nested as a child of line where it should have been as a sibling. For an easier grouping of what svg objects (e.g. line, text and an opaque colour box below text) are used for one single relationship, I also introduced <g> element. 
![image](https://cloud.githubusercontent.com/assets/4427841/22885296/09ef90c0-f1f9-11e6-9519-0514531e7e5f.png)

**Comment by ronhitchens** [comment]
This seems ok, closing
