### ISSUE TITLE
Double click on node with all outbound links already displayed should do nothing

### ISSUE THREAD

**Issue by ronhitchens** [overstory/sw-poc#31]

**Comment by smagu** [comment]
Does not do anything, apart from a slight movement due to the fact that double click also "keeps holding a node" for mere milliseconds; this moves graph slightly. 
I went further step ahead and applied same behaviour to radial menu outbound and inbound clicks: if you click of them and there is no data added/removed, the diagram will stay put

**Comment by ronhitchens** [comment]
This looks good now.
