### ISSUE TITLE
When nodes enter/leave the graph, they should not cause all other nodes to reset their positions

### ISSUE THREAD

**Issue by ronhitchens** [overstory/sw-poc#34]
When nodes appear in the graph, they should pop out locally, which may cause nearby nodes to be re-balanced, but the entire graph should not go into wacky rebalancing.

**Comment by smagu** [comment]
Reduced the strength of additional forces, reduced alpha on restart() and increased the gravity force - this is how I believe Neo4J is doing. Any addition/removal (enter() and exit() respectively) will still affect all the graph unless default behaviour is turned off completely. This is due to the fact that forceManyBody works as a clustering force
That being said additions/removals do not have such a strong effect anymore

**Comment by ronhitchens** [comment]
This seems to be working properly now.
